### ISSUE TITLE
Add Promise support to .request methods

### ISSUE THREAD

**Issue by klarstrup** [shopgun/shopgun-js-sdk#5]
Let the `.request` methods of the graphkit and the corekit return a `Promise` when not passed a callback function in the last argument, so as to provide an API like so:
```js
SGN.CoreKit.request({ url: '/v2/catalogs' })
    .then(function(data){/* handle data */})
    .catch(function(error){/* handle error */})
```

Check the environment for support and throw an error if support is not present. Said error should suggest using the callback style or adding a `Promise` polyfill.

**Comment by mortenbo** [comment]
@klarstrup I was wondering if this should be a responsibility of the SDK. If yes, we need to bundle Promise support into the SDK for browser environments, which will increase the bundle size.

**Comment by klarstrup** [comment]
It's easier to let end users(ie. app developers) decide whether they need to support browsers without native `Promise` support and set up the global polyfill if necessary. From our perspective it doesn't make a difference where the support comes from. 

But we should definitely give an error message if they don't provide a callback function and we don't find `Promise` support, something presenting their options: Using the callback style or providing Promise support.

I will try to find a way to easily apply this pattern to all asynchronous methods throughout the kit.

**Comment by mortenbo** [comment]
@klarstrup We should act on this soon or close it, IMO. Perhaps it can do done like AWS S3 where you can call `.promise()` at the end of e.g. `getObject()`.
