### ISSUE TITLE
Issue with catalog sorting

### ISSUE THREAD

**Issue by KristofferKN** [shopgun/shopgun-js-sdk#65]
We don't seem to be able to change the order of our catalogs when getting them from the following endpoint:
https://api.etilbudsavis.dk/v2/catalogs?dealer_id=XXXXX&order_by=-publication_date&r_locale=en_US

Whether we put "order_by=publication_date" or "order_by=-publication_date", it stays the same. Also, sometimes the order changes without us changing the order_by parameter.

Do you have any insight as to why we are experiencing this?

**Comment by mekanixdk** [comment]
Confirmed. Looking into it.

**Comment by mekanixdk** [comment]
And fixed.
