### ISSUE TITLE
[PagedPublicationKit] Take a page(not spread) to start on in configuration.

### ISSUE THREAD

**Issue by klarstrup** [shopgun/shopgun-js-sdk#9]
This is hacked in in react-lab like
```js
let versoPosition;
if (this.props.position === 'end') {
  versoPosition = viewer._core.verso.pageSpreads.length - 1;
} else {
  // PagedPublicationKit should expose this sorta thing
  versoPosition = +viewer._core.verso.pageIds[`page${this.props.position}`].id
    .replace('double-', '')
    .replace('single-', '');
}
viewer.navigateTo(versoPosition);
```

**Comment by klarstrup** [comment]
This is already exposed via the `pageId` key on the `initialize` options object. Dunno how I missed it.

**Comment by mortenbo** [comment]
Agreee. This sucks right now. It should be possible to navigate to either a page index or ID easily. Currently, it's only easy if you know the index.

**Comment by mortenbo** [comment]
Yesterday, I added a fix that made sure pageId is moved all the way in: https://github.com/shopgun/shopgun-js-sdk/commit/097bcf3fec34a2ab9f60e5a714ee0456d02eac4d

Also, I need to be better at using GitFlow. Been a one man army for far too long :D
